jwt:
  private:
    key: classpath:private-key.pem
  public:
    key: classpath:public-key.pem
server:
  port: 8082
spring:
  application:
    name: junit-mockito-e-outros
  database:
    driverClassName: org.postgresql.Driver
  datasource:
    password: example
    username: postgres
    url: jdbc:postgresql://localhost:5432/junit-mockito-e-outros?createDatabaseIfNotExist=true&useSSL=false
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: always
