package br.pvv.senai.petshop.common;

public enum Type {
	NORMAL, FOGO, LUTA, AGUA, VOO, GRAMA, VENENO, ELETRICO, TERRA, PSIQUICO, PEDRA, GELO, INSETO, DRAGAO, FANTASMA,
	ESCURIDAO, ACO, FANTASIA, ESTELAR
}
